project:
  type: website

website:
  title: "Blog do Lucas Vasques"
  site-url: https://vasqueslucas.github.io/blog-professor/
  repo-url: https://github.com/vasqueslucas/blog-professor
  repo-branch: main

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

publish:
  gh-pages:
    branch: gh-pages
    repo: vasqueslucas/blog-professor
